[default]
src = 'src'
out = 'out'
libs = ['lib']
remappings = [
    '@openzeppelin/=node_modules/@openzeppelin/',
    '@thirdweb-dev/=node_modules/@thirdweb-dev/',
]

# See more config options https://github.com/gakonst/foundry/tree/master/config